services:
  # ========================================================
  # 1. SETUP: Chỉ chạy 1 lần để tạo chứng chỉ SSL và Mật khẩu, sau đó tự tắt
  # ========================================================
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch-setup
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ x$${ELASTIC_PASSWORD} == x ]; then
          echo "Vui lòng đặt ELASTIC_PASSWORD"; exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: elasticsearch\n"\
          "    dns:\n"\
          "      - elasticsearch\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-data-1\n"\
          "    dns:\n"\
          "      - es-data-1\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-data-2\n"\
          "    dns:\n"\
          "      - es-data-2\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:$${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"$${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    environment:
      - ELASTIC_PASSWORD=elastic11
      - KIBANA_PASSWORD=kibana11


  # ========================================================
  # 2. MASTER NODE: Não bộ điều phối
  # ========================================================
  elasticsearch:
    depends_on:
      - setup
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - es_master_data:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - cluster.name=erp-cluster
      - cluster.initial_master_nodes=elasticsearch
      - discovery.seed_hosts=es-data-1,es-data-2
      - node.roles=master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elastic11
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    healthcheck:
      test: ["CMD-SHELL", "curl -f -k -u elastic:elastic11 https://localhost:9200 || exit 1"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - backend
      - frontend

  # ========================================================
  # 3. DATA NODE 1: Lưu trữ A
  # ========================================================
  es-data-1:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es-data-1
    restart: unless-stopped
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata-zone-a:/usr/share/elasticsearch/data
    environment:
      - node.name=es-data-1
      - cluster.name=erp-cluster
      - discovery.seed_hosts=elasticsearch
      - node.roles=data,ingest
      - node.attr.zone=zone-a
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elastic11
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-data-1/es-data-1.key
      - xpack.security.http.ssl.certificate=certs/es-data-1/es-data-1.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-data-1/es-data-1.key
      - xpack.security.transport.ssl.certificate=certs/es-data-1/es-data-1.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - backend

  # ========================================================
  # 4. DATA NODE 2: Lưu trữ B
  # ========================================================
  es-data-2:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es-data-2
    restart: unless-stopped
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata-zone-b:/usr/share/elasticsearch/data
    environment:
      - node.name=es-data-2
      - cluster.name=erp-cluster
      - discovery.seed_hosts=elasticsearch
      - node.roles=data,ingest
      - node.attr.zone=zone-b
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elastic11
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-data-2/es-data-2.key
      - xpack.security.http.ssl.certificate=certs/es-data-2/es-data-2.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-data-2/es-data-2.key
      - xpack.security.transport.ssl.certificate=certs/es-data-2/es-data-2.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - backend

  # ========================================================
  # 5. KIBANA: Giao diện quản lý Database
  # ========================================================
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    restart: unless-stopped
    volumes:
      - certs:/usr/share/kibana/config/certs
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana11
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    ports:
      - "5601:5601"
    networks:
      - backend
      - frontend

volumes:
  certs:
  es_master_data:
  esdata-zone-a:
  esdata-zone-b:
