services:
  minio:
    image: bitnamicharts/minio:sha256-f651556c9adf011d17e3e1646079f34906ecce43aaf73deeafa08d7a25872db4
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-admin@2025}
    volumes:
      - minio-data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network