services:
  spring-app:
    build:
      context: ../../../
      dockerfile: ../../../Dockerfile
    container_name: spring-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      INTEGRATION_MINIO_URL: http://minio:9000
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_USERNAME: app_cache
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_CACHE_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    deploy:
      resources:
        limits:
          memory: 1024M
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network