include:
  - compose/oracle-db.yml
  - compose/redis.yml
  - compose/zookeeper.yml
  - compose/kafka.yml
  - compose/minio.yml
  - compose/spring-app.yml

volumes:
  oracle-data:
  redis-data:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  minio-data:

networks:
  app-network:
    driver: bridge