KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="kafka"
    password="kafka@2025"
    user_kafka="kafka@2025";
};

internal.KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="kafka"
    password="kafka@2025"
    user_kafka="kafka@2025";
};
